import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "../i18n";
import { TranslationProvider } from "@/context/TranslationContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";

// Existing fonts

// ✅ Add Jost
const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  // weight: ["400", "500", "600", "700"], // you can customize weights
});

export const metadata: Metadata = {
  title: "KidzVoice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${jost.variable} antialiased`}>
        <TranslationProvider>
          <div className="absolute right-4 top-2 z-10">
            <LanguageSwitcher />
          </div>
          {children}
        </TranslationProvider>

        <Toaster />
      </body>
    </html>
  );
}
